spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: '5672'
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints
  endpoint:
    health:
      show-details: always # Show detailed health information
    info:
      enabled: true # Enable the info endpoint
    shutdown:
      enabled: true # Enable the shutdown endpoint
    metrics:
      enabled: true # Enable the metrics endpoint




# docker run -d --name my-rabbit -p 5672:5672 -p 15672:15672 rabbitmq:management-alpine
# access http://localhost:15672/#/







